### ISSUE TITLE
Compiler UI minor issue

### ISSUE THREAD

**Issue by jfrux** [marklagendijk/WinLess#10]
Hey Mark, the only other thing I would consider (for me) a MINOR issue, VERY MINOR...
Is on the Compiler output screen, it's kind of hard to really see the errors.
Maybe some sort of enhanced detail Row View that expands on the output... maybe adds line breaks and a scroll for each object.

This is merely a suggestion, I can always expand the window to see the error details.

I'm sure you also know of most of your improvement goals so sorry if this is one of those obvious ones that you plan on fixing later.

Thanks for all you do.

-Josh

**Comment by marklagendijk** [comment]
I will take a look at it. Seems like something that should be easy to fix.

> I'm sure you also know of most of your improvement goals so sorry if this is one of those obvious ones that you plan on fixing later.

Not really. Suggestions are always welcome.

**Comment by marklagendijk** [comment]
Fixed :). Get 1.5.3 from http://winless.org

**Comment by michaud** [comment]
mark, I made a WPF version of WinLess. It's still rough but it works. I also added some things like being able to show the List vertical & horizontal, changing the default output folder, changing the output folder after you added the folder to WinLess and more. Are you interrested?

**Comment by marklagendijk** [comment]
Sure, show me the magic.

I don't have any experience with WPF myself. But that doesn't matter because I also don't have that much experience with regular Windows Forms.

Does the SingleInstanceController still work?

**Comment by michaud** [comment]
I think I am a little behind with my code, with your latest burst of work so I didn't get to see if that works.
Should I make a fork of WinLess or is WPF a to big of change and just start a new repository?

**Comment by marklagendijk** [comment]
I think a fork should be ok.

What are exactly the advantages of WPF? And how do those advantages make WinLess better?
I'm looking forward to seeing what you did exactly.
