### ISSUE TITLE
WinLess not minifying

### ISSUE THREAD

**Issue by Firesphere** [marklagendijk/WinLess#102]
After upgrading less.js to 1.5.1 (latest, adviced, version), the resulting CSS is not minified anymore.

**Comment by geekcubed** [comment]
Seeing this also. Definitely a breaking change in 1.5.1 (or one of it's dependencies).  Downgrading back to 1.5.0 resolves it

**Comment by sprynm** [comment]
Is this related to:

"In usage, we do no longer support the yui-compress option due to a bug in ycssmin which was not getting fixed. We have switched to clean-css. If you use this option it will use clean-css and output a warning. The new option is called –clean-css."

http://lesscss.org/#changes

**Comment by Firesphere** [comment]
Reinstalling WinLess resolves this problem, but it's not the optimal solution ofcourse.

**Comment by geekcubed** [comment]
@Firesphere are you allowing winless to upgrade the bundled version of Less when you run it though - or sticking with the version bundled in the installer?

**Comment by Firesphere** [comment]
I update when the system says there's an update. This includes bundled versions of external systems.

**Comment by michaelthorne** [comment]
Yup. Also experiencing the same problem.

WinLess version: 1.8.2
LESS.js version: 1.6.0

I've tried uninstalling and reinstalling without any luck.

Any ideas?

**Comment by marklagendijk** [comment]
The problem is indeed that the name of the less.js minify parameter changed. This should be fixed in WinLess.

**Comment by michaelthorne** [comment]
@marklagendijk Thanks for the reply! Any idea on a possible ETA for a fix?

Thanks for a great app!

**Comment by marklagendijk** [comment]
Yep. ETA is a couple of minutes ago.

**Comment by Firesphere** [comment]
Heh, nice one, thank you!

**Comment by michaelthorne** [comment]
Thanks!

**Comment by ghost** [comment]
This issue is back with v1.8.3 and re-installing WinLess did not help.

Also, when re-installing WinLess, all folders/settings are lost. Not funny.

**Comment by imshuffling** [comment]
Yup, same issue here... anyone have a link to download v1.6?

**Comment by ghost** [comment]
I stopped using WinLess all together now.
Now using the less compilers and css compression stuff in PhpStorm (File Watchers).
