### ISSUE TITLE
Twitter Bootstrap not compiling

### ISSUE THREAD

**Issue by jfrux** [marklagendijk/WinLess#11]
I'm now getting a compiler error as follows:
8:31:26 AM  <my path>less\style.less    ErrorOR:
  type: Syntax
  message: 'eval' is null or not an object
  filename: <my path>less\style.less
  column: -1

I've determined it to be something in Twitter Bootstrap:
`.ie7-inline-block() {
  *display: inline; /* IE7 inline-block hack */
  *zoom: 1;
}`

**Comment by marklagendijk** [comment]
Duplicate of #1.
