### ISSUE TITLE
&:extend(.clearfix all) not working in winless

### ISSUE THREAD

**Issue by ArnoMandersTfe** [marklagendijk/WinLess#113]
First thing to say is that winless is a very cool tool. Now I encounterd a problem. 

If I use the latest bootstrap (bootstrap-3.1.1) the grid isn't working anymore because winless is ignoring the extend clearfix. First i updated the less.js to the newest version. This doesn't work so i updated the whole winless app. Still no result.

If this is the less:

.container{
    margin: 20px;
    &:extend(.clearfix all);
}

the css outputs like this:
.container{
   margin: 20px;
}

**Comment by marklagendijk** [comment]
Fixed in 1.9.0, which is now released!
