### ISSUE TITLE
Does not compile when minify is on

### ISSUE THREAD

**Issue by marcusds** [marklagendijk/WinLess#115]
With WinLess 1.8.3 using Less 1.7.0, files will not compile if minify is on. Though they say they do in the log, successfully. If you uncheck minify, they compile fine however.

**Comment by matthias-maier** [comment]
I have the same problem.

**Comment by artoodetoo** [comment]
Me too. The worst thing is minify option is on by default. 
I'm first trying WinLess and cannot see results at all until found this issue.

**Comment by ArturKwiatkowski** [comment]
I have the same issue since the last update of LESS to 1.7.0.

**Comment by marklagendijk** [comment]
For now I advise to either downgrade to LESS 1.6 by reinstalling WinLess, and disabling LESS update notifictations, or to not use minify.
I am currently working on [WinLess 2](https://github.com/marklagendijk/WinLess/tree/winless2), which will be released within a few weeks.

**Comment by michaelthorne** [comment]
@marklagendijk Awesome. Thanks!

**Comment by Tomicapo** [comment]
Same problem. Using on Windows 7. 
Only compiles when "minify" option is off.
When "minify" is on, I get a success message but no file is written.
On another computer running Windows 8 it's working perfectly.
I'm going back to previous version on win 7...

**Comment by jeepstone** [comment]
Thank you for your email.

I am out of the office until Monday 14th April. Please contact Steve Tustin on 01242 573311 for any urgent enquiries.

Kind regards,
Pete

**Comment by ghost** [comment]
Same problem here. Using version 1.8.3 with less.js 1.7.0

**Comment by exaviore** [comment]
Same issue here. Can't wait for WinLess 2.

**Comment by michaelthorne** [comment]
Guys, I know it's not a fix to the problem, but a change in workflow might be worthwhile. I was a huge fan of WinLess, it is a great tool. However, for a free "tool", which does have these odd issues, it's not practical to have it effect your work.

So I've moved over to Grunt for LESS compilation, specifically:
- https://github.com/gruntjs/grunt-contrib-connect Creates a static web server
- https://github.com/gruntjs/grunt-contrib-watch Runs tasks whenever files change
- https://github.com/gruntjs/grunt-contrib-less Compiles LESS

And the other benefit of this workflow is that you can always use the latest version of LESS, without waiting for the app to be updated.

**Comment by nickelfault** [comment]
Still an issue :(

**Comment by bibi-babi** [comment]
the important thing is that the adjust issue in the next relase (relatively short). :)

**Comment by marklagendijk** [comment]
Fixed in 1.9.0, which is now released!
