### ISSUE TITLE
Specify output file folder/name

### ISSUE THREAD

**Issue by Ixonal** [marklagendijk/WinLess#117]
The structure of my project currently has my css and less files split into different folders, and sometimes with different names (for example, I compile bootstrap styles from less and rename such that theme.less becomes bootstrap-theme.css). It would be nice to be able to specify what the output folder/name for compilation so that the project structure won't be determined by this application's compilation. Maybe an enhancement for version 2?

**Comment by marklagendijk** [comment]
This is already possible in the WinLess 1. When you right-click on a file you get a context menu, which also contains the option 'Select output file'.

**Comment by Ixonal** [comment]
Well I'll be, so it does. Might want to write up some quick documentation on that, because it's not really obvious that the option exists.

**Comment by marklagendijk** [comment]
This will be better / more intuitive in WinLess 2.

**Comment by Ixonal** [comment]
ok, cool.
