### ISSUE TITLE
Twitter Bootstrap background-image: url() wrong root path

### ISSUE THREAD

**Issue by johanbove** [marklagendijk/WinLess#12]
WinLESS version 1.5.3
Less.js version 1.3.0

I have copied Twitter Bootstrap LESS files in a folder outside my site's less files for easier customization of Twitter Bootstrap.

I am referring to the LESS files in this folder:

```
/assets/lib/bootstrap/less/
```

My _bootstrap.less_ file and _variables.less_ files are in the folder:

```
/assets/less/
```

I am referring from my variables.less file to Twitter Bootstrap's:

``` css
// Get default Bootstrap variables 
@import "../lib/bootstrap/less/variables.less";
```

I didn't change the LESS CSS declaration in _variables.less_:

``` css
@iconSpritePath:          "../img/glyphicons-halflings.png";
```

CSS declaration in _sprites.css_:

``` css
.icon-white {
  background-image: url("@{iconSpritePath}");
}
```

After compilation using WinLESS the path turns into this:

``` css
background-image: url("../lib/bootstrap/less/../lib/bootstrap/less/../img/glyphicons-halflings.png");
```

Expected output:

``` css
background-image: url("../img/glyphicons-halflings.png");
```

It seems like WinLESS is adding the path to the root automatically to the CSS.

When compiling with _less.js_ the path is correct.

``` css
background-image: url("http://localhost:8080/assets/lib/bootstrap/img/glyphicons-halflings.png");
```

**Comment by johanbove** [comment]
Seems like this is a LESS.js issue. I found a work-around here: https://github.com/cloudhead/less.js/issues/294

**Comment by Irvanabdurrahman** [comment]
great, good job guys..!!
