### ISSUE TITLE
Winless.org doesn't work

### ISSUE THREAD

**Issue by geminic** [marklagendijk/WinLess#133]
Why the official site does not work for several weeks?

**Comment by sprynm** [comment]
Comes up immediately for me.

**Comment by marklagendijk** [comment]
Also works for me. @geminic what is the problem you're having?

**Comment by geminic** [comment]
It is very strange. Site is unavailable for me in Russia for several weeks. I try different browsers, computers, internet-providers. Links to dowload from this site does not work also.

**Comment by marklagendijk** [comment]
That is very strange indeed. Sounds like the website is being censored.
What do you get when you open [87.253.142.76](http://87.253.142.76/) in your browser? If you get 'Apache is functioning normally' then that would imply that at least the server is not blocked by IP address.
If you can access the IP address, you might be able to access the website if you use an alternative DNS server.

**Comment by geminic** [comment]
Thank you. IP is also unavailable for me. But I got access the site by anonymizer.
What a strange problem! This tool: http://ping-admin.ru/ (it's on Russian) shows, that winless.org is unavailable for some regions of Russian Federation. I don't know why.
