### ISSUE TITLE
Won't compile after update to less 1.7.5

### ISSUE THREAD

**Issue by magicbruno** [marklagendijk/WinLess#138]
I've updated less compiler to 1.7.5. Updating was successful, but now, when i try to compile and compress nothing happens. No compilation. No error.
Il I remove the compress option, files are successfully compiled.
My system: Windows 7 64 bit. I'm using winless in background with Visual Studio 2012 running and Web Essentials extension active. 
Workaround: currently I'm use Web Essentials to compress compiled CSS files.

**Comment by magicbruno** [comment]
Two problems:
- Css compressin via lessc now use less css-clean less plugin
- Command line argument are changed.
  I have modified source and recomiled and now works. See my fork https://github.com/magicbruno/WinLess

**Comment by vadmkp** [comment]
After updating LESS.js to 1.7.5 does not work. To update you need to run the program as Administrator. Perhaps, after the update change the access rights to a file? But this is only a suggestion. The program is great and I hope you manage to solve this problem.

**Comment by magicbruno** [comment]
Winless use "lessc" command to compile and compress your less files. With less 1.7.5 compress process is changed. 
1. You need to install css-clean less plugin
2. Compress arguments parameter are changed (view http://lesscss.org/usage/#v2-upgrade-guide).
Workaround: 
Clone my WinLess Github fork (https://github.com/magicbruno/WinLess), build project in Visual Studio 2012 and use the executable built in the /bin/Release or /bin/Debug folder. 
I simply changed properties of Winless.lnk that Winless installer puts in Start Menu so it points to new Winless.exe. It's working form me.
However, If you don't compress compiled files, compiler works properly.
Hope this helps.

**Comment by magicbruno** [comment]
Inmy WinLess Github fork (https://github.com/magicbruno/WinLess), i've added Installable executable.

**Comment by vadmkp** [comment]
Thank's . It is work as you said. But only if i run vs as administrator then work perfectly. Thank's again.

**Comment by magicbruno** [comment]
I've added InstallShield Express project and installable exe.
https://github.com/magicbruno/WinLess
