### ISSUE TITLE
Multiple @import directives are duplicating (mixin) rules in compiled CSS

### ISSUE THREAD

**Issue by basher** [marklagendijk/WinLess#14]
Hi Mark,

I have a structure like this in my main LESS file:

@import "base";
@import "600-up";
@import "900-up";

Each of these modular LESS files imports a single "mixins.less" file.
The compiled CSS has duplicated CSS - eg:

h1 {
  font-size: 36px;
  font-size: 3.6rem;
  font-size: 36px;
  font-size: 3.6rem;
  font-size: 36px;
  font-size: 3.6rem;
}

This is related to this Less.js issue - https://github.com/cloudhead/less.js/issues/49
which is fixed here - https://github.com/cloudhead/less.js/commit/cb789334233e377bd91a17d3118a0424ad167929.

Are there any plans to incorporate this fix into WinLess?

Many thanks,
Kev.

**Comment by marklagendijk** [comment]
WinLess comes with the latest distributions of less.js. The fix you mentioned isn't in the latest release yet.

**Comment by basher** [comment]
Thanks Mark. I have now commented on the less.js issue asking for an update.

btw, WinLess is awesome.

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
