### ISSUE TITLE
How do I update {less} to version 2.1.0 in the winless 1.9?

### ISSUE THREAD

**Issue by maxsite** [marklagendijk/WinLess#142]
How do I update {less} to version 2.1.0 in the winless 1.9?

**Comment by marklagendijk** [comment]
https://github.com/marklagendijk/WinLess#using-a-globally-installed-less

Updating the globally installed less can be done with `npm update less -g`.

**Comment by maxsite** [comment]
This does not work. Less is 1.7.5

**Comment by marklagendijk** [comment]
Did you follow all the instructions of the link?

**Comment by maxsite** [comment]
Update did, but still winless sees only 1.7.5. In the settings «Use globale installed less» not checked.

**Comment by marklagendijk** [comment]
You _should_ check `use global installed less` if you want to use the globally installed less, instead of the one packaged with WinLess ;).

**Comment by maxsite** [comment]
How to make less 2.1.0 complete WinLess? Without globally installed.
