### ISSUE TITLE
@import options bug v1.9

### ISSUE THREAD

**Issue by PseudoNinja** [marklagendijk/WinLess#143]
WinLess version: 1.9.0
LESS.js version: 1.7.5

Hypothesis: 
When a less file imports another less file that is also imported as a reference by a third file, the file imported (and used as reference) is ignored in import.

Example:

```
    File1.less
    @import file2.less
    @import file3.less

    File2.less
    @import (reference) file3.less
```

How it should work:
File 3 is loaded as a reference to file 2 but also imported once with file1.

How it is working:
File 3 is loaded as a reference and ignored as an import to file 1.

**Comment by marklagendijk** [comment]
This would be a bug in LESS.js instead of WinLess. You could [try the newest version of LESS.js](https://github.com/marklagendijk/WinLess#using-a-globally-installed-less) and see if that fixes it.

**Comment by PseudoNinja** [comment]
Will do, thanks.
