### ISSUE TITLE
WinLess.org is blocked for Russian users?

### ISSUE THREAD

**Issue by SerNeo** [marklagendijk/WinLess#146]
Hi,
I'm from Russia and I can't open WinLess.org and I've tested pings from different locations and almost all cities of Russia have no response to your domain. 
WinLess.org is blocked for Russian users?

**Comment by marklagendijk** [comment]
Apparently, yes, but not by me. Also see #133. It seems that mr. Putin doesn't like WinLess ;).

**Comment by SerNeo** [comment]
Thx for answer! 
This is really strange because my Internet provider's support was saying that it's probably hosting is blocking RU IP's. Could you ask your hosting about this issue? and I'll ask my provider to check it again bc I really like WInLess!
