### ISSUE TITLE
Incorrect handling of calc()

### ISSUE THREAD

**Issue by vo-borodin** [marklagendijk/WinLess#161]
Error when using the function calc() for recalculation of sizes. I wrote in .less file the following code:
.css-class {
  height: calc(100% - 226px);
}
After compilation, in .css file there was:
.css-class {
  height: calc(-126%);
}

**Comment by MitchellBouwman** [comment]
The "calc(x)" cannot calculate percentages and pixels. You need to use jQuery/Javascript for that.

**Comment by piyushwalia** [comment]
Try this
`height: calc(~"100% - 226px")`

**Comment by ghost** [comment]
Try this:
`width: ~"calc(100% - 69px)"`

**Comment by vo-borodin** [comment]
Thanks for hints, it works
