### ISSUE TITLE
Name 'lessc' is not recognized...

### ISSUE THREAD

**Issue by Wierzchu** [marklagendijk/WinLess#162]
Hello,
I downloaded WinLess, I added folder with less file to compile and when I click to "Compile", I have error in polish language:

> "Nazwa 'lessc' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne.
> program wykonywalny lub plik wsadowy."

In english it means something like this:

> Name 'lessc' is not recognized as internal or external command.
> executable program or batch file.

What can I do to compile this file to CSS?

**Comment by MitchellBouwman** [comment]
Go to File > Settings and uncheck the "Use globally installed Less" ;)
Than it will use it's own less compiler.

**Comment by Wierzchu** [comment]
Wow, fast answer :) 
Thank you @MitchellBouwman , It's working now :+1:

**Comment by MitchellBouwman** [comment]
Great! Enjoy ;)
