### ISSUE TITLE
change output-encoding

### ISSUE THREAD

**Issue by toooue** [marklagendijk/WinLess#21]
Is there some setting of output-Ecoding?

My Windows's default-encoding is Shift-JIS.
When the CSS written in UTF-8 changed by WinLess, the output is Shift-JIS.

How can I change this?

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
