### ISSUE TITLE
An "added value" feature for IE?

### ISSUE THREAD

**Issue by kevadamson** [marklagendijk/WinLess#22]
Thinking it might be nice to have the following optional compiling feature:

User ticks a check-box labeled "Compile for IE" for a .less document, then they add comma separated @media declarations from the document (or some kind of comment hook in the LESS: `/* if for ie */ ... /* end if for ie */` or something?) for the rules they would like compiling into a CSS file for IE8 and under.

This might be especially useful for those who use media query bubbling.

Make sense?

On another note, you could add other non Less related compiling options as well. For example: I use inline-block a lot for layout instead of floats. Could WinLess be used to sniff out all rules containing inline-block, and then output a file that has them all replaced (and comma separated) with display:inline; for IE7 and under?

**Comment by marklagendijk** [comment]
You should use conditional comments for that. With the conditional comments you either include specific IE styleheets, or add IE classes which you use in your regular stylesheet.

**Comment by kevadamson** [comment]
Thanks. Yes I already do. Just thinking of added value.
