### ISSUE TITLE
Eval is null

### ISSUE THREAD

**Issue by mgvez** [marklagendijk/WinLess#23]
Hi,

I have an issue similar to https://github.com/marklagendijk/WinLess/issues/1 but I really don't know why : it does not seem to be bootstrap-related. It seems quite random... I use bootstrap, but only import some of the .less files. Everything worked fine, but at some point, I could not add anything to the global scope anymore.

For example, if I add 
div{
    border:1px red solid;
}
to my .less file, I get the "eval is null" error. But if I remove a comment (that has been there since the beginning) now it parses fine. Also, if I import the whole bootstrap.less file, it also compiles.

Then I do more tests, and at some point (I really don't know why... the file seems to be exactly the same way as it was when it was not compiling : all comments there, bootstrap not imported... nothing changed but maybe a newline or so) the div begins to work again, but I cannot add any variable to the global scope : eval is null. I remove a comment and it works (can be any comment). I thought it might be related to the size of the file, but it does not seem so because if I remove something else than a comment, I get the same error again.

I have winless 1.5.3 with less 1.3.0. I rebooted, I tried to add a dummy line to ie7-inline-block in bootstrap, I even tried renaming my file, also putting it in another folder. I tried saving it in another charset, from another editor, nothing. Tried it on another PC, does'nt work (so it's not my computer that is corrupted). Tried it on a mac with another compiler, works fine.

**Comment by yas4891** [comment]
Seems related to what I am experiencing. 
I am trying to compile "buttons.less" from Bootstrap. 
Did not make any changes to the file (except adding imports for mixins, variables and reset).

**Comment by mgvez** [comment]
I have found out yesterday that when I delete the call to .ie7-restore-left-whitespace(); in btn of buttons.less, the error seems to be gone.

**Comment by nawlbergs** [comment]
You dont have to delete the .ie7-restore-left-whitespace() if you dont want to...
this is really odd... but just delete all the comments out of the .btn class in the button.less file... and it works.
(its the class at the very top... same class that calls the .ie7-restore-left-whitespace() mixin)

**Comment by yas4891** [comment]
@nawlbergs Indeed. Awesome catch. Thanks for the help!

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
