### ISSUE TITLE
Watch an FTP folder

### ISSUE THREAD

**Issue by matsaukeo** [marklagendijk/WinLess#26]
The only way I've managed to do this is to download software that maps an FTP drive to a local drive (eg "z" drive). The problem with this is that my CSS editor warns me that someone else has updated the file. I think what happens is that I update the CSS file, the software uploads to FTP and the editor thinks that was someone else.

If I map an FTP drive as a network drive (which can be done through windows without the need for mapping software) then I can't see that drive when I click "find folder". Is this because it can't see those types of folders? Its there in explorer but not in the winless GUI.

Also thanks for Winless - Its awesome! - Just wish I could sort this one out.

**Comment by marklagendijk** [comment]
I don't think good FTP support is possible (well, everything is possible, but I think it would be, too complex).
The issue with network drives should be fixed sometime.

**Comment by matsaukeo** [comment]
That's OK, I understand and appreciate what you've already done. The FTP software solution seems to work OK for me except when the connection is bad. If FTP support could be inbuilt in future that would be great as I suspect it could be handled better.

**Comment by marklagendijk** [comment]
WinLess 1.7 has proper folder dialog when using 'Add folder'. This should make adding network locations easier.
