### ISSUE TITLE
Should be able to choose the output filename

### ISSUE THREAD

**Issue by AoDev** [marklagendijk/WinLess#27]
Hello I just started to use winless to compile twitter bootstrap with some tuning. 

I like its ability to watch the folder, really nice job , thx :)

At this moment the output file is automatically set this way:  _**.less becomes *_*.css . I can select an output folder but not output filename. Could you implement a  functionality so that we can chose the output filename? 

Example: 

twitter bootstrap has responsive.less and we want the output filename to be bootstrap-responsive.css (not responsive.css)

**Comment by N8-B** [comment]
I've created a bootstrap-responsive.less file in my LESS folder and then add @import "responsive.less"; at the top. Then configure the compiler to output to bootstrap-responsive.css in your CSS folder. Seems to work for me.

**Comment by AoDev** [comment]
Yes this is what it would do, but this is not what I intent to say.

Try to output bootstrap-responsive.less to responsive.css, it can't be done at this time. 

The only output option I have when I do right click on a file is 
"select output folder" 

You could tell me "why do you want a different output filename?" just happened in a particular case in my job. I can manually rename the file after, it's not big deal. 

but,

I would add another option "select output filename" or change current behaviour of "select output folder" so that filename can be specified too.

**Comment by N8-B** [comment]
OK, sorry about that. I misunderstood. You're right. I agree that such an option could be useful.

**Comment by luckyshot** [comment]
+1!

It happens to me in a few projects too and I need to use the alternative SimpLESS for those.

For example, when developing Wordpress themes using Twitter Bootstrap I need to compile "bootstrap.less" into "style.css". 
Another example, in huge projects I sometimes have several LESS files to test file sizes and performance: "dev.less", "dev-no-plugins.less", "production.less" and many others that compile to the same "style.css".

**Comment by luckyshot** [comment]
Great job, thanks a lot Jacob!

**Comment by marklagendijk** [comment]
Has been fixed by merging @jmclocklin commit. Will be included in WinLess 1.7.
