### ISSUE TITLE
css3 webkit-filter: Saturate compile error

### ISSUE THREAD

**Issue by zolitch** [marklagendijk/WinLess#28]
A bit of an odd one this. 

There appears to be a compile error when I include the css3 saturate filter option, The following causes the 'undefined' is null or not an object' error:

``` css
-webkit-filter: saturate(50%);

```

But this compiles fine:

``` css
-webkit-filter: sepia(50%);
```

I have also tried some things which are meaningless:

``` css
background: saturate(50%);
```

Which also fails and:

``` css
-webkit-filter: nothing(50%);
```

which passes.

Which means that it's almost as if 'saturate' is a reserved word or something as it only fails when that word is used?

Thanks.

**Comment by zolitch** [comment]
I've got around this for now by escaping the attribute like so:

``` css
-webkit-filter: ~"saturate(50%)";
```

Saturate could also be an intrinsic less mixin.

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
