### ISSUE TITLE
Character encoding setting

### ISSUE THREAD

**Issue by kuxiongxiong** [marklagendijk/WinLess#3]
it seems that the default output  Character encoding  is ANSI. 
I neet uft-8 coding.so how do i set?

**Comment by marklagendijk** [comment]
Hmm, ANSI seems a strange default.

Anyway, WinLess uses the [script](https://github.com/duncansmart/less.js-windows) from @duncansmart to compile the LESS files. If the (default) character encoding should be changed I think it should happen in there.
