### ISSUE TITLE
Compiler error message

### ISSUE THREAD

**Issue by akobashikawa** [marklagendijk/WinLess#30]
I just installed WinLESS 1.5.3 in Windows 7 Professional and try to compile a .less file.
I get this error:
C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf(9, 10) Windows Script Host: The value for the attribute is not valid : language
I note it is reference to file less.wsf at line:
<script language="jscript">
May be Is it a Windows system error?

**Comment by serhumano** [comment]
i have the same error

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
