### ISSUE TITLE
Compile doesn't work

### ISSUE THREAD

**Issue by opensource21** [marklagendijk/WinLess#32]
I get an "Das Handle konnte nicht ge”ffnet werden, w„hrend das Handle 1 umgeleitet wurde." error, which means 
Couldn't open Handle, while handle 1 is redirected.

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
