### ISSUE TITLE
Spaces in progid:DXImageTransform... parameters

### ISSUE THREAD

**Issue by JonesBen** [marklagendijk/WinLess#33]
Example

`html filter: ~"progid:DXImageTransform.Microsoft.gradient( startColorstr='"@TopCol~"', endColorstr='"@BottomCol~"',GradientType=0 )";`

produces

`htmlfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr=' #2452cf ', endColorstr=' #2555d8 ',GradientType=0 );`

which causes it not to show correctly in IE (IE only feature).

the correct output should be 
`htmlfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#2452cf', endColorstr='#2555d8',GradientType=0 );`

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
