### ISSUE TITLE
Compile fails when having >= 35 @import rules

### ISSUE THREAD

**Issue by danielfilzhut** [marklagendijk/WinLess#34]
When trying to compile a LESS file with more than 35 @import rules,
compilation fails with the following message:

ErrorOR:
 type: Syntax
 message: 'eval' is null or not an object
 filename c:\web...
 column: -1
 extract: ,,@import "page-basic.less";

Seems to be a problem of the underlying lessc.wsf: Using lessc.wsf standalone also brings up this error.
While other Less1.3-based compilers like SimpLESS are working fine.

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
