### ISSUE TITLE
Retain formatting of compiled LESS files

### ISSUE THREAD

**Issue by badg0003** [marklagendijk/WinLess#35]
This is not so much a bug as a 'nice-to-have'. It would be great if the compiled CSS file(s) that is generated would retain the tabbing/block structure of the LESS file(s). For example, if rules have been indented (as shown in the example below) this would be retained (unless the 'minify' option had been selected)

``` css
.class1 {

}
    .class1 > h1 {

    }
        .class1 > h1 a {

        }
```

**Comment by marklagendijk** [comment]
Not a WinLess issue (WinLess uses less.js for the actual compiling). 
Anyway, what you are asking for doesn't make sense. When using LESS you should only change your LESS code, and never manually change the resulting CSS code.
