### ISSUE TITLE
Asking new feature: shortcuts to compile action in icon tray menu

### ISSUE THREAD

**Issue by AoDev** [marklagendijk/WinLess#36]
Hello I wish we could have a compile button directly in the menu appearing when we do right click on the icon tray.

The main reason is that I cannot use this incredibly useful feature which is watching folder. 

Because I am using git ( but this happens maybe with other version control tools) when I pull, some files are updated, which cause winless to see it and recompile while I am  still in the rebase process. This causes annoying and painful series of commands to get my work directory ok, when I forget to disable winless.

So I thought that a useful  feature would be a one easy click solution trough the icon tray menu. Even a global hotkey, why not? 

I doubt that it's possible to prevent winless from compiling when git is doing its stuff but this would be the best obviously.

I hope to see it someday, thanks for your work :)

**Comment by dashk** [comment]
Aye. Is this what you're referring to? 
https://github.com/marklagendijk/WinLess/pull/37

If so, maybe we can merge the issue/request... Not sure how this is done though. (Github n00b)

**Comment by AoDev** [comment]
Yes this is the feature I'd like to have :)

**Comment by marklagendijk** [comment]
Added in 1.5.4.
