### ISSUE TITLE
Error inside @import not shown

### ISSUE THREAD

**Issue by smhg** [marklagendijk/WinLess#38]
Thanks for WinLess!

When I forget a closing curly bracket inside a file which I import with @import, no error is "thrown".
The WinLess "Compiler" tab shows "success" but the outputted .css file is not changed.

(I'm using version 1.5.3)

Disclaimer: this might be related to less.js rather than WinLess, I haven't tested that.

**Comment by dashk** [comment]
@samhauglustaine Do you have some sample code (Small) that can demonstrate this issue?

**Comment by smhg** [comment]
Absolutely. Create 2 files:

more.less (with a missing curly bracket at the end of evenMore):

```
somethingElse {
    evenMore {
}
```

style.less:

```
@import 'more';

something {
    color: green;
}
```

Add the directory to WinLess and only check "style.less" and Minify for style.less.
On save style.css is not updated (i didn't check created, so you might need to correct the file, save, make some changes and remove the curly bracket at the end of evenMore again).

Other "errors" in more.less might trigger the same behavior.

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
