### ISSUE TITLE
Upgrade less to 1.2.2

### ISSUE THREAD

**Issue by anointed** [marklagendijk/WinLess#4]
Numerous changes have happened since 1.2.
Could you please recompile the installer to use 1.2.2 or provide instructions on how we can manually keep less updated on Windows when the installer was used?

thanks

**Comment by marklagendijk** [comment]
Don't have time right now.

It is easy to upgrade yourself. Just replace the less.js file found at:
C:\Program Files\Mark Lagendijk\WinLess\Less

**Comment by andyr0id** [comment]
Hello,

Upgrading the less.js file to the latest version is nice and easy, thanks Mark!

However, when you do this, the Less version shown in Help > About is incorrect. I can see that this is a hard coded constant value in the app.

As an idea for a future version, it would be good to have this less.js version as a configurable value, or even read from the comments in the less.js file.

**Comment by marklagendijk** [comment]
@andyr0id good idea. I have implemented it.

An update with less.js 1.3.0 will be released shortly. I'm also looking into adding a feature which makes it possible to automatically update less.js, see [this issue](https://github.com/cloudhead/less.js/issues/729).

**Comment by marklagendijk** [comment]
Just released WinLess 1.4.0 which included less.js 1.3.0.
