### ISSUE TITLE
Automatic destination folder

### ISSUE THREAD

**Issue by mgdodge** [marklagendijk/WinLess#42]
My coworkers and I prefer to keep our 'less' folder INSIDE of the 'css' folder instead of at the same level. I think that might be the way CodeKit does it by default, though I could be wrong (I'm a PC guy, the others are OSX). As a feature request, do you think a global preference could be made as follows:

Default compile destination:
- 'css' folder is sibling of 'less' (checked by default)
- 'css' folder is parent of 'less' (unchecked by default)

If there are other common file structures in use, those could be added as well. If you were feeling brave, perhaps an input box where someone can enter a relative path (eg: '../css/' or '../../assets/css/', etc.)

**Comment by marklagendijk** [comment]
Just fixed it. Will be released with WinLess 1.7. It now uses the following logic:

```
if (lessFilePath contains '\less\' and (if 'css' folder exists either on the same level, or as a parent, or as a child of the less folder)){
  use the found css folder
}
else{
  use same folder
}
```
