### ISSUE TITLE
@import "http://www.my-lib.com/lib/base-lib.less"

### ISSUE THREAD

**Issue by yeso** [marklagendijk/WinLess#44]
@import "http://www.my-lib.com/lib/base-lib.less";

don't work in WinLess~
but work by  <script src="js/less-1.3.0.min.js" type="text/javascript"></script> in html page

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
