### ISSUE TITLE
Custom output settings

### ISSUE THREAD

**Issue by pafnuty** [marklagendijk/WinLess#48]
Hello!
Thanks for a great program! Through this program, I started using LESS.
Is it possible to implement this kind of LESS-code:

```
.main {
    color: #000;
    &:hover {
        color: #f96;
    }
    .submain {
        color: #96f;
        &:hover {
            color: #fff;
        }
    }
}
```

to css-code:

```
.main {
    color: #000;
    }
    .main:hover {
        color: #f96;
        }
    .main .submain {
        color: #96f;
        }
        .main .submain:hover {
            color: #fff;
            }
```

styles acquire cascade form.
This approach to writing code handy when working on a project of people who do not use LESS.

P.S. I apologize if the text is hard to read, I use the Google translator

**Comment by marklagendijk** [comment]
Personally I don't think modifying the output of a compiled LESS file is a good idea. If you really want something like this you should request it [here](https://github.com/cloudhead/less.js). WinLESS just uses the original LESS compiler for the actual compiling.
