### ISSUE TITLE
wrong less version reported in about info

### ISSUE THREAD

**Issue by martyvdlinden** [marklagendijk/WinLess#49]
Winless 1.6.0 reports using Less 1.3.0 in the "about" info, should be 1.3.1.
As far as i can tell it only reports using 1.3.0 while actualy running 1.3.1.

**Comment by marklagendijk** [comment]
You are right. This seems to be an error in the latest release of the[ less.js node package](https://npmjs.org/package/less). It will probably be fixed in a next less.js release.
