### ISSUE TITLE
error: lessc.wsf(0, 1) Windows Script Host: :jscript

### ISSUE THREAD

**Issue by 4ll4n** [marklagendijk/WinLess#5]
Fresh install of Winless 1.3.0 after removing previous version.
Getting this error:

`C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf(0, 1) Windows Script Host: :jscript`

Compiling with Duncan Smart's less.js for Windows works.

**Comment by marklagendijk** [comment]
Where are you getting this error? As a dialog box, or as a compile error?

**Comment by 4ll4n** [comment]
It's a compile error.

On 19 Mar 2012, at 23:22, Mark Lagendijk
reply@reply.github.com
wrote:

**Comment by marklagendijk** [comment]
In that case try whether your LESS code is causing the problem. If so I would have to see the code to see what's going wrong.

**Comment by 4ll4n** [comment]
The code doesn't seem to be causing the problem since I can compile
the exact same files using the command line.

On 20 Mar 2012, at 21:51, Mark Lagendijk
reply@reply.github.com
wrote:

**Comment by marklagendijk** [comment]
Actually WinLess also compiles via duncan's script. But if you use another version of less.js with that script as WinLess does, it still might be the code which causes the problem. I'm not saying that the code is wrong, it could be a problem in less.js.

I will be releasing a new version of WinLess shortly. Try it and see if the problem still exists.

**Comment by marklagendijk** [comment]
WinLess 1.4.0 has been released. Please try it and see whether the problem still exists.

**Comment by 4ll4n** [comment]
Thanks Mark but same error pops up.

On 22 March 2012 14:23, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
Please try to compile a very simple less file. For example:

test.less

``` css
body {
    width: 2 + 2px;
}
```

Does it give the same error if you just try to compile this test.less file?

**Comment by 4ll4n** [comment]
Indeed it does.

On 22 March 2012 15:16, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
Ok. Sounds like somehow your installation is corrupted and reinstalling doesn't fix it.

Could you try the following:
1.  Uninstal WinLess
2.  Delete 'C:\Program Files (x86)\Mark Lagendijk' if it still exists.
3.  Reinstall WinLess.
4.  Check whether it works now.

**Comment by 4ll4n** [comment]
Still no luck I'm afraid. :(

On 22 March 2012 15:28, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
Hmm, did you ever have WinLess working at all?

The only other thing I can think of is that is some kind of file permissions (read/write) issue. It might be that WinLess (actually the less.wsf script which WinLess calls via the command line) is restricted from either reading the LESS file or writing the css file.

Could you try compiling a simple less file located on your desktop?

**Comment by 4ll4n** [comment]
It was working up until a few weeks ago.
It seems you're onto something with file permissions. Files compile
successfully if I run the program as admin.

On 22 March 2012 15:39, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
Ok. Try to find out which of the following is causing the problem:
1. The LESS files you are trying to compile (or writing the css files in the output folder)
2. The files inside 'C:\Program Files (x86)\Mark Lagendijk\Less'

You can try this by setting the file permissions to full control.

**Comment by 4ll4n** [comment]
I've tried setting permissions on all files in 'C:\Program Files (x86)\Mark
Lagendijk\' and my less folder to allow full control for all users and
explicitly adding my self as a user but no luck.

On 22 March 2012 15:59, Mark Lagendijk <
reply@reply.github.com

**Comment by marklagendijk** [comment]
If it does work when you run as admin, it must be a permissions issue. If you won't succeed in fixing it I'm afraid your only option will be to run WinLess as admin.

Since you are the only one with this issue, and because I can't reproduce it, I won't be able to find out what the bug is and fix it. If you do get it fixed, let me know how you did it.

**Comment by 4ll4n** [comment]
Thanks for all your help. I'll keep trying when I get a min.

On 22 March 2012 17:24, Mark Lagendijk <
reply@reply.github.com

**Comment by KlausKurzawa** [comment]
Sorry but I got the same error with my fresh install (my windows vista home premium x64 is swedish so error messages are in swedish)

WinLess version: 1.5.4
LESS.js version: 1.3.1

Time    File    Compiler Result
19:16:42    D:\inetpub\wwwroot\fotbollz2.se\assets\less\bootstrap.less  C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf(16, 6) (null): Biblioteket är inte registrerat. (Eng: Library not registred)

C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf(9, 20383) Körningsfel i Microsoft JScript: 'document' är null eller inte ett objekt (eng document is null or not an object)

C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf(103, 6) Körningsfel i Microsoft JScript: 'fso' är null eller inte ett objekt (eng: fso is null or not an object)

If I run it manually: cscript //nologo "C:\Program Files (x86)\Mark Lagendijk\WinLess\Less\lessc.wsf" D:\inetpub\wwwroot\fotbollz2.se\assets\less\bootstrap.less it works

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).
