### ISSUE TITLE
cannot call method charAt

### ISSUE THREAD

**Issue by vasilyevd** [marklagendijk/WinLess#50]
# COMPILE SUCSEFULL

.redactor {
    li {
        font-weight: bold;
    }
}
@media all {
    and (-webkit-min-device-pixel-ratio: 1.5) {
            .redactor;
        }
}
# TAKE ERROR

.redactor {
    li {
        font-weight: bold;
    }
}

@media all {
    and (-webkit-min-device-pixel-ratio: 1.5) {
            .redactor li;
        }
}

**Comment by marklagendijk** [comment]
I don't think '.redactor li;' is valid LESS syntax. Anyway, since WinLess just uses the original LESS compiler, compiling issues should be reported [here](https://github.com/cloudhead/less.js).
