### ISSUE TITLE
Sharing WinLess configurations/settings among users

### ISSUE THREAD

**Issue by mcacek** [marklagendijk/WinLess#53]
I don't see any way to share my WinLess settings.  It would be great if I could share my settings with other users but I am unable to find a way to do so.  The file paths for the other users will be exactly the same and it would be very nice if I could simply pass around a config file for my projects.  Is this possible?  If not, could it be?

**Comment by marklagendijk** [comment]
Yes, this is possible. You can find the WinLess settings file at: `%APPDATA%\WinLess\WinLess\1.8.0.0\data`
