### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by nomadpgmr** [marklagendijk/WinLess#63]
It would be nice to know when a new version is available and where to go to get it.
1. Add link in help menu to http://winless.org/

Add one or more of following
2. Show Current Released version and Current Installed Version in about screen. Could include a link to new version in help screen.
3 Somehow display if a new version is available. This can be via a Display of the current released and current installed version on startup or a small status line below the files dialog, a popup on start-up, or on the help menu. 
5. Add link in help menu to latest download (github).

Thanks!

**Comment by marklagendijk** [comment]
Double post
