### ISSUE TITLE
Winless changing image names from bold to 700

### ISSUE THREAD

**Issue by ralani** [marklagendijk/WinLess#66]
I was trying to convert from using simpless to winless but one thing has put me off. I have an image named "delete-bold.png" and Winless is changing this to delete-700.png, this forces me to change my image names to avoid the word "bold" which I don't find particularly appealing.

**Comment by marklagendijk** [comment]
I am unable to reproduce the issue which you describe. I tried different approaches, but in all instance the 'bold' part is left intact. Can you give me an code example?

**Comment by ralani** [comment]
I cannot replicate either anymore which is really strange! I just tried again and it is working now, maybe there was a syntax error that caused winless to bug out. Thanks!
