### ISSUE TITLE
calc issue

### ISSUE THREAD

**Issue by Diablohu** [marklagendijk/WinLess#68]
either calc(100% + 1rem) and ~"calc(100% + 1rem)" will output calc(100%+1rem) which is invalid for CSS3

but calc(100% - 1rem) outputs the correct result calc(100% - 1rem)

**Comment by marklagendijk** [comment]
WinLESS uses the official LESS compiler. This issue is only occurring when minification is enabled. 
So this seems to be an issue with the CSS minification library which the official LESS compiler uses.
