### ISSUE TITLE
Update less to chosen version

### ISSUE THREAD

**Issue by mgvez** [marklagendijk/WinLess#69]
It would be a great improvement if we could decide the less version that winless uses. As of writing this, the 1.4 version of less is in beta state, so winless only updates to the dev version of 1.3. I need the features of less 1.4 for a project I'm doing, but there's no way I can manually update less to that version, which is is real pain.

**Comment by gnomishperson** [comment]
Within your WinLess install directory, you can download the latest version of less.js and replace the files within the /node_modules/less directory of your WinLess install. WinLess should then grab the correct 1.4 version, you can verify this via the Help -> About menu in the WinLess app.

**Comment by marklagendijk** [comment]
@gnomishperson thanks for replying to this issue.

Because WinLess includes NPM to update to the latest stable version of LESS, there is an even easier way.
1. Run cmd as administrator
2. `cd c:\Program Files (x86)\Mark Lagendijk\WinLess`
3. `node_modules\.bin\npm install less@beta`
4. Open WinLess and go to Help -> About to verify the result.

**Comment by smajl** [comment]
@marklagendijk Thanks for pointing this out. LESS is now 1.4.0 official and WinLess was not updating correctly so I performed manual update (just `npm install less` in WinLess directory).

**Comment by magikMaker** [comment]
Still it would be really great to add an option to settings where it is possible to choose the version. For certain projects it is also necessary to _downgrade_ to a specific version.

@gnomishperson I don't quite understand where to place the less.js file I downloaded from lesscss.org. The folder `/node_modules/less` contains many, many files.

**Comment by gnomishperson** [comment]
@magikMaker It's best to include the contents of the whole repo: https://github.com/less/less.js/archive/master.zip which is what that `/node_modules/less` folder consists of. Or as @marklagendijk noted just use the `npm install less` method above.

**Comment by magikMaker** [comment]
@gnomishperson Excellent! Thank you for a quick reply.

If anyone else is insterested, here's how to install a specific  version with npm: https://npmjs.org/doc/install.html

In my case I need the 1.3.0 version: `npm install less@1.3.0`

worked like a charm! :+1:

**Comment by srhise** [comment]
Nice work all. I am now able to switch between versions using this technique.

**Comment by jeepstone** [comment]
I find that if I update to Less 1.7 using either NPM or by just dropping the files in, Winless updates to 1.7 but I'm then unable to write my compiled CSS files to the server. They compile correctly but nothing is output. The individual LESS files all compile on their own. I'm guessing this is a permissions issue somewhere?

**Comment by ghost** [comment]
@jeepstone I am experiencing the same thing. I used the instructions in this thread to manually update WinLess to LESS.js 1.7 to fix an error that I was receiving when compiling. I no longer receive the error, but the CSS output file does not appear to be overwritten with the latest compiled version. Running WinLess as an administrator makes no difference, in my case.

**Comment by marklagendijk** [comment]
Removed support for updating the bundled less, in version 1.9.0. Instead you can now choose to use the globally installed less.
