### ISSUE TITLE
command line issues

### ISSUE THREAD

**Issue by walterzhang** [marklagendijk/WinLess#7]
I create a simple  winless-build-system in sublime-text2

use the command line: WinLess.exe -d ${file_path}

when i run the build system once, then winless will create a instance.

run three time, i get three instance,

and then i press ctrl+s, three winless complie .less file together.

I think that's not reasonable, winless should have ignored repeated folder, and should exist only one instance program.

i love winless, I hope you can understand my meaning, my English is very poor.... :-(

**Comment by marklagendijk** [comment]
I agree that WinLess should be single instance. I have fixed this and released a new version: [WinLess 1.5.1](http://winless.org)

Be sure to check the changed command line paramaters [here](http://files.web-mark.nl/winless/WinLess_command_line_arguments.txt) (or execute 'WinLess.exe --help').
