### ISSUE TITLE
Winless, Dreamweaver and Skydrive

### ISSUE THREAD

**Issue by Johns3n** [marklagendijk/WinLess#72]
Whenever i save my less files in dreamweaver in a skydrive folder, winless doesn't compile the files! However if I edit my files in lets say another css editor like Crunch! Winless compiles right away with a save in a skydrive path. Is this a dreamweaver problem or winless problem with skydrive?

**Comment by marklagendijk** [comment]
Sounds like it is an issue with Dreamweaver. WinLESS uses an default system component to 'listen' to changes of files within certain folders. Somehow Dreamweaver succeeds in saving files without Windows picking this up.

I don't think WinLess can do anything about this.
