### ISSUE TITLE
Update of LESS.js not working

### ISSUE THREAD

**Issue by smajl** [marklagendijk/WinLess#75]
There is new 1.4.0 version of LESS (which I really need to use). WinLess detects new version and offers an update from 1.3.3 -> 1.4.0, but when it finishes it says "updated to 1.3.3" and there is still the old version.

PS: I have manually updated by going to: `path\to\your\WinLess` and running `npm install less` ;)

**Comment by kazooter** [comment]
Also had this problem.  Uninstalled v1.3.3., downloaded and installed v1.8.0.  Stills says v1.3.3 and wants me to update to v1.4.0.

**Comment by nawlbergs** [comment]
same.

**Comment by marklagendijk** [comment]
WinLess 1.8.1 has been released. This version comes with less.js 1.4.1 and a partial fix for the update bug. Updating less.js now works, but only when WinLess is run as admin. See #82 for more info.

**Comment by gicalle** [comment]
same problem when updating from less 1.4.1 to 1.6.1.

message keeps saying:

```
Succesfully updated less.js to version 1.4.1
```

after running winless as administrator, problem was solved (update succeeded).

possible solution/workaround: add to the message window some extra info

```
in case of problems updating less file, please try running winless as admin
```

or something similar.

**Comment by srad** [comment]
Current version asked me to update from 1.6.0 to 1.7.4 but still stays on 1.6.0 after the "successful" update and on every restart keeps going to do it again.

**Comment by gicalle** [comment]
First close the application. Then run it 'as administrator' and the update will work.
