### ISSUE TITLE
Minify but keep /* comments */

### ISSUE THREAD

**Issue by irunatbullets** [marklagendijk/WinLess#8]
Hi there,
I was wondering if you could include an option to Winless that maintains CSS comments when minifying?

**Comment by marklagendijk** [comment]
At the moment this is not possible. The reason for this is that WinLess compiles with the official compiler: [less.js](http://lesscss.org). As long as less.js doesn't offer this option, WinLess won't either.

**Comment by Sjeiti** [comment]
Strange, since lesscss.org states 'CSS-style comments are preserved by LESS'. Maybe it's a new feature.
