### ISSUE TITLE
Winless 1.8 don't update less 1.3.3 to 1.4.1

### ISSUE THREAD

**Issue by rhermann** [marklagendijk/WinLess#80]
On checking for updates there appears the question for update to 1.4.1, I click Yes and it will only update 1.3.3. So it do not work.

**Comment by arechsteiner** [comment]
Can confirm this

**First mesage:**
_WinLess uses the official LESS compiler, less.js, to compile your LESS files._
_A new version of less.js is available. Do you want to update less.js from 1.3.3 to 1.4.1?_

**Second message:**
_Succesfully updated less.js to version 1.3.3_

**Comment by isour2** [comment]
Confirm this

**Comment by leedorian** [comment]
Confirm this too.

**Comment by carcoral** [comment]
Confirm this too, any updates on it?

**Comment by marklagendijk** [comment]
This issue is related to the rights with which the Node Package Manager is run.
I tried to fix this by running the npm command elevated, but even then it only works if WinLess itself was started elevated :S.
I'm not sure when I will have time to finish fixing it.

**Comment by marklagendijk** [comment]
Duplicate of #75.
