### ISSUE TITLE
Program Stopped Working

### ISSUE THREAD

**Issue by nitrojane** [marklagendijk/WinLess#81]
Environment: Win 8 Pavillion Desktop PC

Installed and used WinLess for nearly a week then today after an automatic compile I noticed that the webpages were not updating. I found the less.js needed updated message and did that. When I manually or automatically compile the desired file the program goes to Not Responding. Have tried repairing the program, install/re-install, changing directories for files and nothing makes a difference. The Windows event listing shows that the application is hanging but nothing else of value.
Any idea what I can do next?

Thanks in advance.

**Comment by nitrojane** [comment]
Used a couple of other programs on the project and found that there was a compile error. Where this program goes into a loop and quits responding the other programs identified the problem. Would recommend a fix to recognize and report problems rather than simply 'locking up'.

Thanks,

**Comment by marklagendijk** [comment]
I would recommend specifying with which code this occurs, so I can try to reproduce it ;).

**Comment by nitrojane** [comment]
I'll try to come up with the conditions again and send that - other compile errors since the original problem I was experiencing indicate a compile error so the particular problem was specific to the specific error - sorry if that rambling doesn't make sense...hopefully the gray cells will recall what I did.

**Comment by marklagendijk** [comment]
Try the new 1.9.0 and see if it is fixed.
