### ISSUE TITLE
Updating less.js only works when WinLess is run as administrator

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/WinLess#82]
Updating less.js only works when WinLess is run as administrator. The update messages don't mention this.

This should be properly fixed.

Note: I already implemented running the update command as administrator (using 'run as'). Although this does work, the update itself doesn't. I have no idea why it helps to start WinLess as an admin.

**Comment by Geotex** [comment]
If you are using Windows 8.1, locate winless.exe in c:\Program Files(x86)\Mark Langendijk\WinLess. WinLess.exe>Properties>Compatibility, then run the compatibility trouble shooter. You may have to run it once to get the pane to actually set the paramaters to run in Win7 compatibility mode, and check the "needs additional permissions" box. After doing this and running the test program, you should find it will update less.js properly. I could not update, leaving me at less 1.6. After doing the above, now am current with less 1.7

**Comment by marklagendijk** [comment]
Removed support for updating less in the 1.9.0 release. Added option to use globally installed less, instead.
