### ISSUE TITLE
Minified files seem broken

### ISSUE THREAD

**Issue by brgrz** [marklagendijk/WinLess#86]
When using the minify option and then opening the file in VS, it will show error on the one minified line that gets generated.

When hitting "format selection" VS will format it and show several more errors like incorrectly nested classes.

I found this out when compiling Bootstrap's bootstrap.less file.

If I turn the minify off, everything is fine.

**Comment by marklagendijk** [comment]
WinLess uses less.js (the official LESS compiler) to compile LESS files. Less.js just switched to using another css minifier, this might fix the problem.
If not, it is an less.js issue, and not a WinLess one.
