### ISSUE TITLE
Ability to make mass changes to "Output Folder"

### ISSUE THREAD

**Issue by jfrux** [marklagendijk/WinLess#9]
First things first, this is simply the BEST windows LESS compiler there is...
SimpLESS is dumb... :p

That being said...
When I add my folder, it assumes I want to put all my "css" output in the same folder as my "less" files.
This doesn't align with my workflow really.

I have tons of less files, and each time I load a new site...
I have to right click and change each one individually to "Select Output"

Can this be fixed easily or is it a big fix?

**Comment by marklagendijk** [comment]
> First things first, this is simply the BEST windows LESS compiler there is...
> SimpLESS is dumb... :p

Glad you like it. Don't hate on SimpLESS though,

> I have tons of less files, and each time I load a new site...
> I have to right click and change each one individually to "Select Output"

Having 'tons' of LESS files is quite common. It isn't that common, however, to have 'tons' of CSS files. Are you sure you need all the different CSS files, and couldn't have 1 LESS file which combines them by using '@import's?

> Can this be fixed easily or is it a big fix?

This could be implemented quite easily. I would add an 'context menu' on the directory list with an menu-item 'Select output folder for all files'.

**Comment by jfrux** [comment]
Thanks for getting back to me on this.
Sorry, I wasn't really "hating"... I guess I just didn't see the charm in it... :-\

I guess you're right on the CSS files, wasn't really thinking about it like that...
I guess if you're just making separate CSS files for all of your objects in a web application there could still be quite a few separate ones but sounds like you have a plan.

Whatever makes the most sense to you, I'll roll with it.

Also, I found the ProgramData folder and edited my XML and it definitely helped me get my situation in order for now.

Thank you again!

Sincerely,
Joshua F. Rountree

**Comment by basher** [comment]
Sorry for opening a duplicate issue... I hadn't spotted this one (and I _did_ look).

Where I work, we need to have separate CSS files (and lots of them in different module-specific folders) for our CMS.
Each file may or may not have dependencies, which are then "imported" using a custom packager script.
Also, individual pages / user controls can link to individual CSS files as required.

We than concatenate/minify all CSS and JS on the page when it renders.

So, for us, it would be really useful to be able to select multiple LESS files and output to a folder in 1 go.

**Comment by jonschlinkert** [comment]
I know this is marked as closed, but I actually think adding a context menu with the option to output all to a specific folder would be really helpful.  If a use case would help, the reason I'd find it valuable is that during development I like to keep "wip" less files separate from the production less/css. In other words, this is how I sandbox the less files for new components I'm working on. I have each wip less file import the variables and mixins directly so it can compile to css independently - making it easier to tweak and isolate problems. Once something meets my standards it gets imported into the main .less file.

**Comment by marklagendijk** [comment]
The right solution for this issue would be:
1. Add an extra menu-item 'Select output folder for all files' should be added.
2. This menu-item should pop-up an VistaFolderBrowser dialog.
3. After selecting a new folder the folder-part of all files should be changed to the new folder.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
