### ISSUE TITLE
Not updating to latest less.js (1.5.0)

### ISSUE THREAD

**Issue by ghost** [marklagendijk/WinLess#93]
When opening the 'about', Winless says there is a new version of less.js and if I want to update from 1.4.1 to 1.5.0.
After clicking on yes, it says: Succesfully updated less.js to version 1.4.1

So it doesn't seem to update.

**Comment by j-gardner** [comment]
This is a duplicate issue. Please see https://github.com/marklagendijk/WinLess/issues/85
