### ISSUE TITLE
Using the Minify option when compiling removes @import statements for standard CSS

### ISSUE THREAD

**Issue by charlieTheBotDev** [marklagendijk/WinLess#98]
I have several files that are all imported into a .less file which I then compile to generate a single .css file for my site.

The issue I'm having is that when I include a standard .css file and use the minify option, I lose the @import tag entirely so the code is not used.

If I turn off the minify option, the @import appears at the start of the file as expected.

The syntax I've tried are below:
@import url("styles.css");
@import "styles.css";
@import (css) "styles.css";
@import (css) "styles";

I would use @import (less) "styles.css"; and have the styles inline but the compiler throws errors for the browser hacks that are in the file (I didn't build the site and would never have put them in to start with but they have to stay unfortunately)

**Comment by marklagendijk** [comment]
SHould be fixed in 1.8.3
